function u = Homework_02_Q2_Exact_Solution(x, p, q, r, alpha, beta)
% Exact solution to u'' + p u' + q u = r, u(a) - u'(a) = alpha, u(b) = beta
% Obtained using Mathematica and converted using ToMatlab
u = real((1/2).*exp(1).^((-1/2).*p).*q.^(-1).*(exp(1).^((-1/2).*(p.^2+(-4) ...
  .*q).^(1/2).*((-3)+x)+(-1/2).*p.*x).*(alpha.*q+(-1).*r)+exp(1).^( ...
  p+(-1/2).*p.*x+(1/2).*(p.^2+(-4).*q).^(1/2).*(3+x)).*(beta.*q+(-1) ...
  .*r)+(-1).*exp(1).^((1/2).*p).*r+exp(1).^((1/2).*p+2.*(p.^2+(-4).* ...
  q).^(1/2)).*r+exp(1).^((1/2).*((-1).*p.*x+(p.^2+(-4).*q).^(1/2).*( ...
  1+x))).*((-1).*alpha.*q+r)+exp(1).^(p+(-1/2).*(p.^2+(-4).*q).^( ...
  1/2).*((-1)+x)+(-1/2).*p.*x).*((-1).*beta.*q+r)).*((-1)+coth(( ...
  p.^2+(-4).*q).^(1/2))));
end